//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 11:57:24 AM IST 
//


package me.anichakra.poc.pilot.framework.instrumentation.mock.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ge.cse.framework.instrumentation.mock.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ge.cse.framework.instrumentation.mock.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MockResponse }
     * 
     */
    public MockResponse createMockResponse() {
        return new MockResponse();
    }

    /**
     * Create an instance of {@link MockRequest }
     * 
     */
    public MockRequest createMockRequest() {
        return new MockRequest();
    }

}
