//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.09 at 11:57:24 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/ge/cse/commons/framework/instrumentation/mock/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package me.anichakra.poc.pilot.framework.instrumentation.mock.model;
