server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
#      authentication-database: pilot
#      username: 
#      password:
      database: pilot
  aop:
    auto: true
    proxy-target-class: true

rule:
  file-path: ${RULE_FILE_PATH:rule/vehicle-rules.xls}
  template-class: me.anichakra.poc.pilot.vehicle.rule.VehicleRuleTemplate
  engine: OPENL_TABLETS_ORG

instrumentation:
  name: pilot-vehicle-service
  version: 1.0
  environment: DEV
  remote-address-header: X-Forwarded-For
  user-header: X-USER
  enabled: true
  instance-id: 11
  start-time: 12-May-2019
  ignore-duration-in-millis: 20
  handlers:
    log:
      layers:
      - FILTER
      - CONTROLLER
      - SERVICE
      - REPOSITORY
      event-names: all
      ignore-parameters: false
      ignore-outcome: true
      ignore-exception-stack: false
      limited: false
    new-relic:
      event-names: none
    aws-sns:
      event-names: sourcing
    tracing:
      metrics: 
      - NAME
      - VERSION
      - INSTANCE_ID
      - TRACE_ID
      - CORRELATION_ID
      - USER_ID
      - LOCAL_ADDRESS
      - REMOTE_ADDRESS
      - URI
      event-names: tracing
      
message:
  validations:
    getVehicle.id: Vehicle Id should be more than ${value}.
    searchVehicle.manufacturer.Size: Manufacturer name must be between ${min} and ${max}. Provided number ${input} is invalid.
    searchVehicle.manufacturer.Pattern: At least 4 digit/alphabetic chars is required
    vehicle.manufacturer.Size: Manufacturer name must be between ${min} and ${max}. Provided number ${invalidValue} is invalid.
    vehicle.manufacturer.Empty: Manufacturer cannot be empty
    vehicle.year.Min: Vehicle year should start from at least ${value}
  exceptions:
   - name: VehicleNotFoundException
     code: getVehicle.notFound
     http-status: BAD_REQUEST
     template: Vehicle ${id} is not found
   - name: java.lang.Exception
     code: exception.unknown
     http-status: INTERNAL_SERVER_ERROR
     template: Unknown System Exception
