server:
  port: ${PORT:8080}

# Remove this configuration if want to run with in memory database called H2.
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true

# Postgres connectivity details here      
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DATABASE:postgres}
    username: ${POSTGRES_USER:anirbanchakraborty}
    password: ${POSTGRES_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
  aop:
    auto: true
    proxy-target-class: true

# Path of vehicle.xls file containing the rule template
rule:
  file-path: ${RULE_FILE_PATH:rule/vehicle-rules.xls}
  template-class: me.anichakra.poc.pilot.vehicle.rule.VehicleRuleTemplate
  engine: OPENL_TABLETS_ORG
  
instrumentation: 
  filter:
    enabled: true 
  aspect:
    enabled: true
    ignore-duration-in-millis : 20
  handlers:
    log:
      layers: 
       - FILTER
       - CONTROLLER
       - SERVICE
       - REPOSITORY
      event-names: all
      ignore-parameters: false
      ignore-outcome: true
      ignore-exception-stack: true
      limited: false
    new-relic:
      event-names: none   
    aws-sns:
      event-names: sourcing

 
    
    
    

      