server:
  port: ${PORT:8080}

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

# Postgres connectivity details here      
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/postgres
    username: ${POSTGRES_USER:anirbanchakraborty}
    password: ${POSTGRES_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver

service:
  context-path: /@project.name@/@project.version@

# Path of vehicle.xls file containing the rule template
rule:
  template-path: file://${RULE_TEMPLATE_PATH:/Users/anirbanchakraborty/git/pilot/pilot-service/pilot-vehicle-service/src/main/resources}/vehicle-rules.xls
